version: "3.8"

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    image: cudl/cudl-viewer
    volumes:
      - cudl-data:/srv/cudl-viewer/cudl-data/
      - cudl-viewer-content:/srv/cudl-viewer/cudl-viewer-content/
    ports:
      - "8080:8080"
    depends_on:
      - cudl-db
      - cudl-deploy-data
      - cudl-xtf

  cudl-deploy-data:
    build:
      context: .
      dockerfile: docker/deploy-data/Dockerfile
      args:
        SSH_PUB_KEY: |-
          ${SSH_PUB_KEY}
        SSH_PRV_KEY: |-
          ${SSH_PRV_KEY}
    image: cudl/cudl-deploy-data
    volumes:
       - cudl-data:/srv/cudl-viewer/cudl-data/
       - cudl-viewer-content:/srv/cudl-viewer/cudl-viewer-content/
    depends_on:
      - cudl-db

  cudl-db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: cudl/cudl-db
    restart: always
    volumes:
      - cudl-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cudl
      POSTGRES_DB: cudl
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD:-password}
    ports:
      - ${CUDL_DB_HOST_PORT:-0}:5432

  cudl-image-server:
    build:
      context: .
      dockerfile: docker/image-server/Dockerfile
    image: cudl/cudl-image-server
    environment:
      CANTALOUPE_VERSION: 4.1.6
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

    ports:
      - "8182:8182"

  cudl-xtf:
    image: cudl/cudl-xtf:latest
    ports:
      - 8082:8080
    volumes:
      - cudl-data:/srv/cudl/cudl-data/json
      - xtf-webapp:/opt/xtf/
      - cudl-indices:/srv/cudl/xtf/

  xtf-indexer-cron:
    image: cudl/xtf-indexer-cron:latest
    depends_on:
      - cudl-xtf
    volumes:
      - cudl-data:/srv/cudl/cudl-data/json
      - xtf-webapp:/opt/xtf/
      - cudl-indices:/srv/cudl/xtf/

volumes:
  cudl-data:
  cudl-viewer-content:
  cudl-db:
  xtf-webapp:
  cudl-indices:

