version: "3.7"

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    image: cudl/cudl-viewer
    volumes:
      - cudl-data:/srv/cudl-viewer/cudl-data/
      - cudl-viewer-content:/srv/cudl-viewer/cudl-viewer-content/
    ports:
      - "8080:8080"
    depends_on:
      - cudl-db
      - cudl-deploy-data

  cudl-deploy-data:
    build:
      context: .
      dockerfile: docker/deploy-data/Dockerfile
      args:
        SSH_PUB_KEY: |-
          ${SSH_PUB_KEY}
        SSH_PRV_KEY: |-
          ${SSH_PRV_KEY}
    image: cudl/cudl-deploy-data
    volumes:
       - cudl-data:/srv/cudl-viewer/cudl-data/
       - cudl-viewer-content:/srv/cudl-viewer/cudl-viewer-content/
    depends_on:
      - cudl-db

  cudl-db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: cudl/cudl-db
    restart: always
    volumes:
      - cudl-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cudl
      POSTGRES_DB: cudl
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD:-password}
    ports:
      - ${CUDL_DB_HOST_PORT:-0}:5432


#  imageserver:
#    image: klokantech/iiifserver-iipimage-jpeg2000:latest
#    ports:
#      - 80:80
#    volumes:
#      - ./dropzone/:/dropzone/
#      - ./data/:/data/

volumes:
  cudl-data:
  cudl-viewer-content:
  cudl-db:

