version: "3"

services:
  tomcat:
    image: tomcat:9.0.39-jdk11-openjdk-buster
    volumes:
      - ./target/FoundationsViewer.war:/usr/local/tomcat/webapps/ROOT.war
      - ./docker/tomcat-context.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml
      - ${CUDL_VIEWER_CONFIG:-./docker/cudl-global.properties}:/etc/cudl-viewer/cudl-global.properties
      - ${CUDL_VIEWER_DATA:-../cudl-data/}:/srv/cudl-viewer/cudl-data/
      - ${CUDL_VIEWER_CONTENT:-../cudl-viewer-content/}:/srv/cudl-viewer/cudl-viewer-content/
    ports:
      - "8888:8080"
    depends_on:
      - cudl-db
  cudl-db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: cudl
      POSTGRES_DB: cudl
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD:-password}
    ports:
      - ${CUDL_DB_HOST_PORT:-0}:5432
